"""
core/export.py — Package a trained session as a deployable ZIP.

The ZIP contains:
  vector_store/   FAISS index files
  config.json     Bot configuration
  server.py       Standalone FastAPI server
  widget.html     Copy-paste chat widget (demo + embed snippet)
  requirements.txt
  .env.example
  README.md       Deployment instructions
"""

import io
import json
import zipfile
from pathlib import Path

import config


# ── Server template ────────────────────────────────────────────────────

_SERVER_PY = '''"""
RAG Chatbot Server — generated by RAG Chatbot Builder
Configuration is read from config.json at startup.

Setup
-----
  pip install -r requirements.txt
  cp .env.example .env        # fill in your API keys
  uvicorn server:app --host 0.0.0.0 --port 8000

Endpoints
---------
  POST /chat    body: {"message": "...", "history": [...]}
  GET  /health  returns {"status": "ok", "bot": "..."}
"""

import json
import os
from pathlib import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

BASE = Path(__file__).parent

with open(BASE / "config.json", encoding="utf-8") as _f:
    CFG = json.load(_f)


# ── Embeddings ─────────────────────────────────────────────────────────

def _embeddings():
    provider = CFG.get("embedding_provider", "openai")
    if provider == "openai":
        from langchain_openai import OpenAIEmbeddings
        return OpenAIEmbeddings(
            model="text-embedding-3-small",
            openai_api_key=os.getenv("OPENAI_API_KEY", ""),
        )
    from langchain_community.embeddings import HuggingFaceEmbeddings
    return HuggingFaceEmbeddings(
        model_name=CFG.get("local_embedding_model",
                           "sentence-transformers/all-MiniLM-L6-v2"),
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},
    )


# ── Vector store ───────────────────────────────────────────────────────

from langchain_community.vectorstores import FAISS

_store = FAISS.load_local(
    str(BASE / "vector_store"),
    _embeddings(),
    allow_dangerous_deserialization=True,
)


# ── LLM ───────────────────────────────────────────────────────────────

def _llm():
    provider = CFG.get("llm_provider", "openai")
    model    = CFG.get("llm_model", "gpt-4o-mini")
    if provider == "openai":
        from langchain_openai import ChatOpenAI
        return ChatOpenAI(
            model=model,
            temperature=0.2,
            openai_api_key=os.getenv("OPENAI_API_KEY", ""),
            streaming=True,
        )
    from langchain_community.chat_models import ChatOllama
    return ChatOllama(
        model=model,
        base_url=os.getenv("OLLAMA_BASE_URL", "http://localhost:11434"),
        temperature=0.2,
        streaming=True,
    )

_llm_instance = _llm()


# ── FastAPI ────────────────────────────────────────────────────────────

app = FastAPI(title=CFG.get("bot_name", "RAG Chatbot"))

# allow_origin_regex=".*" covers every origin including
# the special "null" origin that browsers send for file:// pages.
app.add_middleware(
    CORSMiddleware,
    allow_origin_regex=".*",
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)


class ChatRequest(BaseModel):
    message: str
    history: list = []


import re as _re
from fastapi.responses import HTMLResponse

@app.get("/", response_class=HTMLResponse)
def widget():
    """Serve the chat widget at the server root (same-origin, zero CORS issues)."""
    html = (BASE / "widget.html").read_text(encoding="utf-8")
    # Rewrite the hardcoded localhost URL to a relative path so the
    # browser calls /chat on the same origin instead of a full URL.
    html = _re.sub(r\'var API = "[^"]*";\', \'var API = "/chat";\', html)
    return html


@app.post("/chat")
def chat(req: ChatRequest):
    # Retrieve relevant chunks
    scored = _store.similarity_search_with_relevance_scores(req.message, k=5)
    relevant = [(d, s) for d, s in scored if s >= 0.20]
    if not relevant and scored:
        relevant = scored[:1]

    # Build context block
    parts = []
    for i, (doc, _s) in enumerate(relevant, 1):
        fname = doc.metadata.get("source_file", "")
        page  = int(doc.metadata.get("page", 0)) + 1
        parts.append(f"[{i}] Source: {fname}, page {page}\\n{doc.page_content}")
    context = "\\n\\n---\\n\\n".join(parts) if parts else "(No relevant documents found.)"

    # Build messages
    from langchain_core.messages import AIMessage, HumanMessage, SystemMessage

    system_text = (
        f"You are {CFG[\'bot_name\']}, an AI assistant.\\n\\n"
        f"{CFG[\'system_prompt\']}\\n\\n"
        "RULES:\\n"
        "1. You are an AI. You do not have a phone number, email, address, age, body, "
        "feelings, or any other personal attributes. If asked for something personal "
        "that only a human or real company would have, clarify you are an AI "
        "and offer to help with what the user actually needs.\\n"
        "2. For greetings and questions about your name, role, or what you can help with: "
        "respond naturally and helpfully.\\n"
        "3. Factual questions: base your answer ONLY on the Document context below. "
        "Never mix up your own identity with information that appears in the documents.\\n"
        "4. Topics not in documents: say so specifically, e.g. \\"I don\'t have information about [topic]\\".\\n"
        "5. Keep answers concise (1-4 sentences unless more is requested).\\n"
        "6. Reply in the same language the user used.\\n\\n"
        f"Document context:\\n{context}"
    )

    msgs = [SystemMessage(content=system_text)]
    for m in req.history[-8:]:
        role    = m.get("role", "user")
        content = m.get("content", "")
        msgs.append(
            HumanMessage(content=content)
            if role == "user"
            else AIMessage(content=content)
        )
    msgs.append(HumanMessage(content=req.message))

    def stream():
        for chunk in _llm_instance.stream(msgs):
            if chunk.content:
                yield chunk.content

    return StreamingResponse(stream(), media_type="text/plain; charset=utf-8")


@app.get("/health")
def health():
    return {"status": "ok", "bot": CFG.get("bot_name")}
'''


# ── Requirements ───────────────────────────────────────────────────────

_REQUIREMENTS_TXT = """\
fastapi>=0.110.0
uvicorn[standard]>=0.27.0
langchain>=0.2.0
langchain-openai>=0.1.0
langchain-community>=0.2.0
langchain-core>=0.2.0
faiss-cpu>=1.8.0
sentence-transformers>=3.0.0
torch>=2.0.0
openai>=1.20.0
python-dotenv>=1.0.0
pydantic>=2.0.0
"""


# ── .env.example ───────────────────────────────────────────────────────

_ENV_EXAMPLE = """\
# Copy this file to .env and fill in your values.

# Required only when llm_provider or embedding_provider is "openai"
OPENAI_API_KEY=sk-...

# Required only when llm_provider is "ollama"
OLLAMA_BASE_URL=http://localhost:11434
"""


# ── Deploy README ──────────────────────────────────────────────────────

_DEPLOY_README = """\
# {bot_name} — Deployment Guide

Generated by **RAG Chatbot Builder**.

---

## Quick Start

```bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Configure environment
cp .env.example .env
# Edit .env — add OPENAI_API_KEY if you use OpenAI

# 3. Start the server
uvicorn server:app --host 0.0.0.0 --port 8000

# 4. Open http://localhost:8000 in your browser to test the chat widget
#    (do NOT open widget.html as a file — browsers block that)
```

---

## Testing the Widget

After starting the server, open **http://localhost:8000** in your browser.
This serves the widget directly from the server (same-origin), so there are
no browser security blocks.

> Do **not** open `widget.html` as a local file — browsers treat `file://`
> pages as an untrusted origin and will block the fetch request.

---

## Embedding the Chat Widget on Your Webpage

Open `widget.html` and copy everything between
`<!-- WIDGET START -->` and `<!-- WIDGET END -->`.
Paste it into your webpage's `<body>`.

Then update the `API` constant inside the script to your **public** server URL:

```js
var API = "https://your-server.com/chat";
```

---

## API Reference

### `POST /chat`
Send a message and receive a streamed plain-text response.

**Body**
```json
{{
  "message": "Hello, what can you help me with?",
  "history": [
    {{"role": "user",      "content": "previous question"}},
    {{"role": "assistant", "content": "previous answer"}}
  ]
}}
```

**Response** — `text/plain` stream (tokens arrive as they are generated)

---

### `GET /health`
```json
{{"status": "ok", "bot": "{bot_name}"}}
```

---

## Deployment Options

| Platform     | Notes                                      |
|--------------|--------------------------------------------|
| **Render**   | Free tier, easy GitHub deploy              |
| **Railway**  | Free starter plan, zero config             |
| **Fly.io**   | Generous free tier, global edge            |
| **VPS/VM**   | Full control, run `uvicorn` as a service   |

### Docker (optional)

```dockerfile
FROM python:3.11-slim
WORKDIR /app
COPY . .
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
```

```bash
docker build -t {bot_name_slug}-bot .
docker run -p 8000:8000 --env-file .env {bot_name_slug}-bot
```

---

## LLM Provider Notes

- **OpenAI** — set `OPENAI_API_KEY` in `.env`. Works on any server, no GPU needed.
- **Ollama** — requires Ollama installed and running on the same machine.
  Pull the model first: `ollama pull {llm_model}`

## Embedding Model Notes

- **OpenAI** — uses `text-embedding-3-small`. Requires `OPENAI_API_KEY`.
- **Local** — downloads `{local_embedding_model}` on first startup (~90 MB). No API key needed.
"""


# ── Widget HTML ────────────────────────────────────────────────────────

_WIDGET_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{bot_name} — Chat Widget</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: system-ui, -apple-system, sans-serif; background: #f0f2f5;
            display: flex; align-items: center; justify-content: center; min-height: 100vh; }}
    .demo-note {{ color: #888; font-size: 13px; text-align: center; line-height: 1.6; padding: 20px; }}
    code {{ background: #e4e7ec; border-radius: 3px; padding: 1px 5px; font-size: 12px; }}

    /* ── Widget ── */
    #rw {{ position: fixed; bottom: 24px; right: 24px; z-index: 9999;
           font-family: system-ui, -apple-system, sans-serif; }}

    #rw-btn {{
      width: 56px; height: 56px; border-radius: 50%;
      background: #2563eb; color: #fff; border: none; cursor: pointer;
      font-size: 26px; box-shadow: 0 4px 14px rgba(37,99,235,.45);
      display: flex; align-items: center; justify-content: center;
      transition: transform .15s, box-shadow .15s;
    }}
    #rw-btn:hover {{ transform: scale(1.08); box-shadow: 0 6px 18px rgba(37,99,235,.55); }}

    #rw-panel {{
      position: absolute; bottom: 68px; right: 0; width: 360px;
      background: #0f1117; border: 1px solid #2a2f3e; border-radius: 16px;
      box-shadow: 0 8px 40px rgba(0,0,0,.5);
      display: flex; flex-direction: column; overflow: hidden;
      transform-origin: bottom right;
      transition: transform .2s cubic-bezier(.34,1.56,.64,1), opacity .15s;
    }}
    #rw-panel.hidden {{ transform: scale(0.85) translateY(8px); opacity: 0; pointer-events: none; }}

    #rw-head {{
      background: #161b27; padding: 14px 16px; color: #e8eaf0;
      font-weight: 600; font-size: 15px; border-bottom: 1px solid #2a2f3e;
      display: flex; align-items: center; gap: 8px;
    }}
    #rw-head::before {{ content: '●'; color: #4ade80; font-size: 9px; }}

    #rw-msgs {{
      flex: 1; overflow-y: auto; padding: 14px 12px;
      display: flex; flex-direction: column; gap: 10px; min-height: 320px; max-height: 420px;
    }}
    #rw-msgs::-webkit-scrollbar {{ width: 4px; }}
    #rw-msgs::-webkit-scrollbar-thumb {{ background: #3a3f52; border-radius: 4px; }}

    .rw-m {{ max-width: 84%; padding: 9px 13px; border-radius: 12px;
              font-size: 14px; line-height: 1.55; word-break: break-word; white-space: pre-wrap; }}
    .rw-m.u {{ background: #2563eb; color: #fff; align-self: flex-end; border-bottom-right-radius: 3px; }}
    .rw-m.b {{ background: #1a1f2e; color: #dde2f0; align-self: flex-start;
                border: 1px solid #2a2f3e; border-bottom-left-radius: 3px; }}
    .rw-m.b.thinking {{ color: #6b7280; font-style: italic; }}

    #rw-foot {{ padding: 11px; border-top: 1px solid #2a2f3e;
                display: flex; gap: 8px; background: #0f1117; }}
    #rw-inp {{
      flex: 1; background: #1e2433; color: #e8eaf0; border: 1px solid #3a3f52;
      border-radius: 8px; padding: 9px 12px; font-size: 14px; outline: none;
      font-family: inherit;
    }}
    #rw-inp::placeholder {{ color: #5a6278; }}
    #rw-inp:focus {{ border-color: #2563eb; }}
    #rw-go {{
      background: #2563eb; color: #fff; border: none; border-radius: 8px;
      padding: 9px 13px; cursor: pointer; font-size: 17px; line-height: 1;
      transition: background .15s;
    }}
    #rw-go:hover {{ background: #1d4ed8; }}
    #rw-go:disabled {{ background: #374151; cursor: default; }}
  </style>
</head>
<body>
  <p class="demo-note">
    This page demonstrates the <strong>{bot_name}</strong> chat widget.<br>
    Copy everything between <code>&lt;!-- WIDGET START --&gt;</code> and
    <code>&lt;!-- WIDGET END --&gt;</code> into your webpage.
  </p>

  <!-- WIDGET START — paste from here into your page's <body> -->
  <div id="rw">
    <div id="rw-panel" class="hidden">
      <div id="rw-head">{bot_name}</div>
      <div id="rw-msgs"></div>
      <div id="rw-foot">
        <input id="rw-inp" type="text" placeholder="Ask a question…" autocomplete="off">
        <button id="rw-go">&#10148;</button>
      </div>
    </div>
    <button id="rw-btn" title="Chat with {bot_name}">&#128172;</button>
  </div>

  <script>
  (function () {{
    // ↓ Change this to your deployed server URL
    var API = "{api_url}/chat";

    var panel = document.getElementById("rw-panel");
    var btn   = document.getElementById("rw-btn");
    var inp   = document.getElementById("rw-inp");
    var go    = document.getElementById("rw-go");
    var msgs  = document.getElementById("rw-msgs");
    var hist  = [];

    btn.addEventListener("click", function () {{
      panel.classList.toggle("hidden");
      if (!panel.classList.contains("hidden")) inp.focus();
    }});

    function bubble(text, role, extra) {{
      var el = document.createElement("div");
      el.className = "rw-m " + role + (extra ? " " + extra : "");
      el.textContent = text;
      msgs.appendChild(el);
      msgs.scrollTop = msgs.scrollHeight;
      return el;
    }}

    function send() {{
      var text = inp.value.trim();
      if (!text) return;
      inp.value = "";
      go.disabled = true;

      bubble(text, "u");
      hist.push({{ role: "user", content: text }});

      var bot = bubble("Thinking\u2026", "b", "thinking");

      fetch(API, {{
        method: "POST",
        headers: {{ "Content-Type": "application/json" }},
        body: JSON.stringify({{ message: text, history: hist.slice(-8) }})
      }})
      .then(function (res) {{
        if (!res.ok) throw new Error("Server error " + res.status);
        var reader = res.body.getReader();
        var dec = new TextDecoder();
        var answer = "";
        bot.className = "rw-m b";
        bot.textContent = "";
        function read() {{
          reader.read().then(function (x) {{
            if (x.done) {{
              hist.push({{ role: "assistant", content: answer }});
              go.disabled = false;
              inp.focus();
              return;
            }}
            answer += dec.decode(x.value, {{ stream: true }});
            bot.textContent = answer;
            msgs.scrollTop = msgs.scrollHeight;
            read();
          }});
        }}
        read();
      }})
      .catch(function (err) {{
        bot.className = "rw-m b";
        bot.textContent = "\u26a0\ufe0f " + err.message;
        go.disabled = false;
      }});
    }}

    go.addEventListener("click", send);
    inp.addEventListener("keydown", function (e) {{
      if (e.key === "Enter" && !e.shiftKey) send();
    }});
  }})();
  </script>
  <!-- WIDGET END -->
</body>
</html>
"""


# ── Public API ─────────────────────────────────────────────────────────

def create_export_zip(session_id: int, session: dict) -> bytes:
    """
    Build and return a ZIP archive ready to deploy.

    Contents:
      vector_store/   FAISS index files
      config.json     bot config
      server.py       FastAPI server
      widget.html     embeddable chat widget
      requirements.txt
      .env.example
      README.md
    """
    bot_name      = session.get("bot_name", "Bot")
    bot_name_slug = "".join(c if c.isalnum() else "_" for c in bot_name).lower()
    llm_model     = session.get("llm_model", config.OLLAMA_MODEL)
    local_emb     = config.LOCAL_EMBEDDING_MODEL

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:

        # vector store
        store_path = config.VECTOR_STORES_DIR / str(session_id)
        if store_path.exists():
            for fp in store_path.iterdir():
                zf.write(fp, f"vector_store/{fp.name}")

        # config.json
        cfg = {
            "bot_name":            bot_name,
            "system_prompt":       session.get("system_prompt", ""),
            "llm_provider":        session.get("llm_provider", config.LLM_PROVIDER),
            "llm_model":           llm_model,
            "embedding_provider":  session.get("embedding_provider", config.EMBEDDING_PROVIDER),
            "local_embedding_model": local_emb,
        }
        zf.writestr("config.json", json.dumps(cfg, ensure_ascii=False, indent=2))

        # server.py
        zf.writestr("server.py", _SERVER_PY.strip())

        # widget.html
        zf.writestr("widget.html", _WIDGET_HTML.format(
            bot_name=bot_name,
            api_url="http://localhost:8000",
        ))

        # requirements.txt
        zf.writestr("requirements.txt", _REQUIREMENTS_TXT.strip())

        # .env.example
        zf.writestr(".env.example", _ENV_EXAMPLE.strip())

        # README.md (deployment guide)
        zf.writestr("README.md", _DEPLOY_README.format(
            bot_name=bot_name,
            bot_name_slug=bot_name_slug,
            llm_model=llm_model,
            local_embedding_model=local_emb,
        ))

    buf.seek(0)
    return buf.read()
